class FixDatabase < ActiveRecord::Migration
  def change
  	add_column :users, :similarity_0, :real	
  	add_column :users, :similarity_1, :real	
  	add_column :users, :similar_user_1, :string
  	add_column :users, :similarity_2, :real	
  	add_column :users, :similar_user_2, :string
  	add_column :users, :similarity_3, :real	
  	add_column :users, :similar_user_3, :string
  	add_column :users, :similarity_4, :real	
  	add_column :users, :similar_user_4, :string
  	add_column :users, :similarity_5, :real	
  	add_column :users, :similar_user_5, :string
  	add_column :users, :similarity_6, :real	
  	add_column :users, :similar_user_6, :string
  	add_column :users, :similarity_7, :real	
  	add_column :users, :similar_user_7, :string
  	add_column :users, :similarity_8, :real	
  	add_column :users, :similar_user_8, :string
  	add_column :users, :similarity_9, :real	
  	add_column :users, :similar_user_9, :string
  	add_column :users, :similarity_10, :real	
  	add_column :users, :similar_user_10, :string
  	add_column :users, :similarity_11, :real	
  	add_column :users, :similar_user_11, :string
  	add_column :users, :similarity_12, :real	
  	add_column :users, :similar_user_12, :string
  	add_column :users, :similarity_13, :real	
  	add_column :users, :similar_user_13, :string
  	add_column :users, :similarity_14, :real	
  	add_column :users, :similar_user_14, :string
  	add_column :users, :similarity_15, :real	
  	add_column :users, :similar_user_15, :string
  	add_column :users, :similarity_16, :real	
  	add_column :users, :similar_user_16, :string
  	add_column :users, :similarity_17, :real	
  	add_column :users, :similar_user_17, :string
  	add_column :users, :similarity_18, :real	
  	add_column :users, :similar_user_18, :string
  	add_column :users, :similarity_19, :real	
  	add_column :users, :similar_user_19, :string
  	add_column :users, :similarity_20, :real	
  	add_column :users, :similar_user_20, :string
  	add_column :users, :similarity_21, :real	
  	add_column :users, :similar_user_21, :string
  	add_column :users, :similarity_22, :real	
  	add_column :users, :similar_user_22, :string
  	add_column :users, :similarity_23, :real	
  	add_column :users, :similar_user_23, :string
  	add_column :users, :similarity_24, :real	
  	add_column :users, :similar_user_24, :string
  	add_column :users, :similarity_25, :real	
  	add_column :users, :similar_user_25, :string
  	add_column :users, :similarity_26, :real	
  	add_column :users, :similar_user_26, :string
  	add_column :users, :similarity_27, :real	
  	add_column :users, :similar_user_27, :string
  	add_column :users, :similarity_28, :real	
  	add_column :users, :similar_user_28, :string
  	add_column :users, :similarity_29, :real	
  	add_column :users, :similar_user_29, :string
  	add_column :users, :similarity_30, :real	
  	add_column :users, :similar_user_30, :string
  	add_column :users, :similarity_31, :real	
  	add_column :users, :similar_user_31, :string
  	add_column :users, :similarity_32, :real	
  	add_column :users, :similar_user_32, :string
  	add_column :users, :similarity_33, :real	
  	add_column :users, :similar_user_33, :string
  	add_column :users, :similarity_34, :real	
  	add_column :users, :similar_user_34, :string
  	add_column :users, :similarity_35, :real	
  	add_column :users, :similar_user_35, :string
  	add_column :users, :similarity_36, :real	
  	add_column :users, :similar_user_36, :string
  	add_column :users, :similarity_37, :real	
  	add_column :users, :similar_user_37, :string
  	add_column :users, :similarity_38, :real	
  	add_column :users, :similar_user_38, :string
  	add_column :users, :similarity_39, :real	
  	add_column :users, :similar_user_39, :string
  	add_column :users, :similarity_40, :real	
  	add_column :users, :similar_user_40, :string
  	add_column :users, :similarity_41, :real	
  	add_column :users, :similar_user_41, :string
  	add_column :users, :similarity_42, :real	
  	add_column :users, :similar_user_42, :string
  	add_column :users, :similarity_43, :real	
  	add_column :users, :similar_user_43, :string
  	add_column :users, :similarity_44, :real	
  	add_column :users, :similar_user_44, :string
  	add_column :users, :similarity_45, :real	
  	add_column :users, :similar_user_45, :string
  	add_column :users, :similarity_46, :real	
  	add_column :users, :similar_user_46, :string
  	add_column :users, :similarity_47, :real	
  	add_column :users, :similar_user_47, :string
  	add_column :users, :similarity_48, :real	
  	add_column :users, :similar_user_48, :string
  	add_column :users, :similarity_49, :real	
  	add_column :users, :similar_user_49, :string
  	add_column :users, :similarity_50, :real	
  	add_column :users, :similar_user_50, :string
  	add_column :users, :similarity_51, :real	
  	add_column :users, :similar_user_51, :string
  	add_column :users, :similarity_52, :real	
  	add_column :users, :similar_user_52, :string
  	add_column :users, :similarity_53, :real	
  	add_column :users, :similar_user_53, :string
  	add_column :users, :similarity_54, :real	
  	add_column :users, :similar_user_54, :string
  	add_column :users, :similarity_55, :real	
  	add_column :users, :similar_user_55, :string
  	add_column :users, :similarity_56, :real	
  	add_column :users, :similar_user_56, :string
  	add_column :users, :similarity_57, :real	
  	add_column :users, :similar_user_57, :string
  	add_column :users, :similarity_58, :real	
  	add_column :users, :similar_user_58, :string
  	add_column :users, :similarity_59, :real	
  	add_column :users, :similar_user_59, :string
  	add_column :users, :similarity_60, :real	
  	add_column :users, :similar_user_60, :string
  	add_column :users, :similarity_61, :real	
  	add_column :users, :similar_user_61, :string
  	add_column :users, :similarity_62, :real	
  	add_column :users, :similar_user_62, :string
  	add_column :users, :similarity_63, :real	
  	add_column :users, :similar_user_63, :string
  	add_column :users, :similarity_64, :real	
  	add_column :users, :similar_user_64, :string
  	add_column :users, :similarity_65, :real	
  	add_column :users, :similar_user_65, :string
  	add_column :users, :similarity_66, :real	
  	add_column :users, :similar_user_66, :string
  	add_column :users, :similarity_67, :real	
  	add_column :users, :similar_user_67, :string
  	add_column :users, :similarity_68, :real	
  	add_column :users, :similar_user_68, :string
  	add_column :users, :similarity_69, :real	
  	add_column :users, :similar_user_69, :string
  	add_column :users, :similarity_70, :real	
  	add_column :users, :similar_user_70, :string
  	add_column :users, :similarity_71, :real	
  	add_column :users, :similar_user_71, :string
  	add_column :users, :similarity_72, :real	
  	add_column :users, :similar_user_72, :string
  	add_column :users, :similarity_73, :real	
  	add_column :users, :similar_user_73, :string
  	add_column :users, :similarity_74, :real	
  	add_column :users, :similar_user_74, :string
  	add_column :users, :similarity_75, :real	
  	add_column :users, :similar_user_75, :string
  	add_column :users, :similarity_76, :real	
  	add_column :users, :similar_user_76, :string
  	add_column :users, :similarity_77, :real	
  	add_column :users, :similar_user_77, :string
  	add_column :users, :similarity_78, :real	
  	add_column :users, :similar_user_78, :string
  	add_column :users, :similarity_79, :real	
  	add_column :users, :similar_user_79, :string
  	add_column :users, :similarity_80, :real	
  	add_column :users, :similar_user_80, :string
  	add_column :users, :similarity_81, :real	
  	add_column :users, :similar_user_81, :string
  	add_column :users, :similarity_82, :real	
  	add_column :users, :similar_user_82, :string
  	add_column :users, :similarity_83, :real	
  	add_column :users, :similar_user_83, :string
  	add_column :users, :similarity_84, :real	
  	add_column :users, :similar_user_84, :string
  	add_column :users, :similarity_85, :real	
  	add_column :users, :similar_user_85, :string
  	add_column :users, :similarity_86, :real	
  	add_column :users, :similar_user_86, :string
  	add_column :users, :similarity_87, :real	
  	add_column :users, :similar_user_87, :string
  	add_column :users, :similarity_88, :real	
  	add_column :users, :similar_user_88, :string
  	add_column :users, :similarity_89, :real	
  	add_column :users, :similar_user_89, :string
  	add_column :users, :similarity_90, :real	
  	add_column :users, :similar_user_90, :string
  	add_column :users, :similarity_91, :real	
  	add_column :users, :similar_user_91, :string
  	add_column :users, :similarity_92, :real	
  	add_column :users, :similar_user_92, :string
  	add_column :users, :similarity_93, :real	
  	add_column :users, :similar_user_93, :string
  	add_column :users, :similarity_94, :real	
  	add_column :users, :similar_user_94, :string
  	add_column :users, :similarity_95, :real	
  	add_column :users, :similar_user_95, :string
  	add_column :users, :similarity_96, :real	
  	add_column :users, :similar_user_96, :string
  	add_column :users, :similarity_97, :real	
  	add_column :users, :similar_user_97, :string
  	add_column :users, :similarity_98, :real	
  	add_column :users, :similar_user_98, :string
  	add_column :users, :similarity_99, :real	
  	add_column :users, :similar_user_99, :string
  end
end
