class CreateUserSubreddits < ActiveRecord::Migration
  def change
    create_table :user_subreddits do |t|
      t.string :username
      t.string :subreddit_0
      t.integer :num_posts_0
      t.string :subreddit_1
      t.integer :num_posts_1
      t.string :subreddit_2
      t.integer :num_posts_2
      t.string :subreddit_3
      t.integer :num_posts_3
      t.string :subreddit_4
      t.integer :num_posts_4
      t.string :subreddit_5
      t.integer :num_posts_5
      t.string :subreddit_6
      t.integer :num_posts_6
      t.string :subreddit_7
      t.integer :num_posts_7
      t.string :subreddit_8
      t.integer :num_posts_8
      t.string :subreddit_9
      t.integer :num_posts_9
      t.string :subreddit_10
      t.integer :num_posts_10
      t.string :subreddit_11
      t.integer :num_posts_11
      t.string :subreddit_12
      t.integer :num_posts_12
      t.string :subreddit_13
      t.integer :num_posts_13
      t.string :subreddit_14
      t.integer :num_posts_14
      t.string :subreddit_15
      t.integer :num_posts_15
      t.string :subreddit_16
      t.integer :num_posts_16
      t.string :subreddit_17
      t.integer :num_posts_17
      t.string :subreddit_18
      t.integer :num_posts_18
      t.string :subreddit_19
      t.integer :num_posts_19
      t.string :subreddit_20
      t.integer :num_posts_20
      t.string :subreddit_21
      t.integer :num_posts_21
      t.string :subreddit_22
      t.integer :num_posts_22
      t.string :subreddit_23
      t.integer :num_posts_23
      t.string :subreddit_24
      t.integer :num_posts_24
      t.string :subreddit_25
      t.integer :num_posts_25
      t.string :subreddit_26
      t.integer :num_posts_26
      t.string :subreddit_27
      t.integer :num_posts_27
      t.string :subreddit_28
      t.integer :num_posts_28
      t.string :subreddit_29
      t.integer :num_posts_29
      t.string :subreddit_30
      t.integer :num_posts_30
      t.string :subreddit_31
      t.integer :num_posts_31
      t.string :subreddit_32
      t.integer :num_posts_32
      t.string :subreddit_33
      t.integer :num_posts_33
      t.string :subreddit_34
      t.integer :num_posts_34
      t.string :subreddit_35
      t.integer :num_posts_35
      t.string :subreddit_36
      t.integer :num_posts_36
      t.string :subreddit_37
      t.integer :num_posts_37
      t.string :subreddit_38
      t.integer :num_posts_38
      t.string :subreddit_39
      t.integer :num_posts_39
      t.string :subreddit_40
      t.integer :num_posts_40
      t.string :subreddit_41
      t.integer :num_posts_41
      t.string :subreddit_42
      t.integer :num_posts_42
      t.string :subreddit_43
      t.integer :num_posts_43
      t.string :subreddit_44
      t.integer :num_posts_44
      t.string :subreddit_45
      t.integer :num_posts_45
      t.string :subreddit_46
      t.integer :num_posts_46
      t.string :subreddit_47
      t.integer :num_posts_47
      t.string :subreddit_48
      t.integer :num_posts_48
      t.string :subreddit_49
      t.integer :num_posts_49
      t.string :subreddit_50
      t.integer :num_posts_50
      t.string :subreddit_51
      t.integer :num_posts_51
      t.string :subreddit_52
      t.integer :num_posts_52
      t.string :subreddit_53
      t.integer :num_posts_53
      t.string :subreddit_54
      t.integer :num_posts_54
      t.string :subreddit_55
      t.integer :num_posts_55
      t.string :subreddit_56
      t.integer :num_posts_56
      t.string :subreddit_57
      t.integer :num_posts_57
      t.string :subreddit_58
      t.integer :num_posts_58
      t.string :subreddit_59
      t.integer :num_posts_59
      t.string :subreddit_60
      t.integer :num_posts_60
      t.string :subreddit_61
      t.integer :num_posts_61
      t.string :subreddit_62
      t.integer :num_posts_62
      t.string :subreddit_63
      t.integer :num_posts_63
      t.string :subreddit_64
      t.integer :num_posts_64
      t.string :subreddit_65
      t.integer :num_posts_65
      t.string :subreddit_66
      t.integer :num_posts_66
      t.string :subreddit_67
      t.integer :num_posts_67
      t.string :subreddit_68
      t.integer :num_posts_68
      t.string :subreddit_69
      t.integer :num_posts_69
      t.string :subreddit_70
      t.integer :num_posts_70
      t.string :subreddit_71
      t.integer :num_posts_71
      t.string :subreddit_72
      t.integer :num_posts_72
      t.string :subreddit_73
      t.integer :num_posts_73
      t.string :subreddit_74
      t.integer :num_posts_74
      t.string :subreddit_75
      t.integer :num_posts_75
      t.string :subreddit_76
      t.integer :num_posts_76
      t.string :subreddit_77
      t.integer :num_posts_77
      t.string :subreddit_78
      t.integer :num_posts_78
      t.string :subreddit_79
      t.integer :num_posts_79
      t.string :subreddit_80
      t.integer :num_posts_80
      t.string :subreddit_81
      t.integer :num_posts_81
      t.string :subreddit_82
      t.integer :num_posts_82
      t.string :subreddit_83
      t.integer :num_posts_83
      t.string :subreddit_84
      t.integer :num_posts_84
      t.string :subreddit_85
      t.integer :num_posts_85
      t.string :subreddit_86
      t.integer :num_posts_86
      t.string :subreddit_87
      t.integer :num_posts_87
      t.string :subreddit_88
      t.integer :num_posts_88
      t.string :subreddit_89
      t.integer :num_posts_89
      t.string :subreddit_90
      t.integer :num_posts_90
      t.string :subreddit_91
      t.integer :num_posts_91
      t.string :subreddit_92
      t.integer :num_posts_92
      t.string :subreddit_93
      t.integer :num_posts_93
      t.string :subreddit_94
      t.integer :num_posts_94
      t.string :subreddit_95
      t.integer :num_posts_95
      t.string :subreddit_96
      t.integer :num_posts_96
      t.string :subreddit_97
      t.integer :num_posts_97
      t.string :subreddit_98
      t.integer :num_posts_98
      t.string :subreddit_99
      t.integer :num_posts_99
      t.string :subreddit_100
      t.integer :num_posts_100
      t.string :subreddit_101
      t.integer :num_posts_101
      t.string :subreddit_102
      t.integer :num_posts_102
      t.string :subreddit_103
      t.integer :num_posts_103
      t.string :subreddit_104
      t.integer :num_posts_104
      t.string :subreddit_105
      t.integer :num_posts_105
      t.string :subreddit_106
      t.integer :num_posts_106
      t.string :subreddit_107
      t.integer :num_posts_107
      t.string :subreddit_108
      t.integer :num_posts_108
      t.string :subreddit_109
      t.integer :num_posts_109
      t.string :subreddit_110
      t.integer :num_posts_110
      t.string :subreddit_111
      t.integer :num_posts_111
      t.string :subreddit_112
      t.integer :num_posts_112
      t.string :subreddit_113
      t.integer :num_posts_113
      t.string :subreddit_114
      t.integer :num_posts_114
      t.string :subreddit_115
      t.integer :num_posts_115
      t.string :subreddit_116
      t.integer :num_posts_116
      t.string :subreddit_117
      t.integer :num_posts_117
      t.string :subreddit_118
      t.integer :num_posts_118
      t.string :subreddit_119
      t.integer :num_posts_119
      t.string :subreddit_120
      t.integer :num_posts_120
      t.string :subreddit_121
      t.integer :num_posts_121
      t.string :subreddit_122
      t.integer :num_posts_122
      t.string :subreddit_123
      t.integer :num_posts_123
      t.string :subreddit_124
      t.integer :num_posts_124
      t.string :subreddit_125
      t.integer :num_posts_125
      t.string :subreddit_126
      t.integer :num_posts_126
      t.string :subreddit_127
      t.integer :num_posts_127
      t.string :subreddit_128
      t.integer :num_posts_128
      t.string :subreddit_129
      t.integer :num_posts_129
      t.string :subreddit_130
      t.integer :num_posts_130
      t.string :subreddit_131
      t.integer :num_posts_131
      t.string :subreddit_132
      t.integer :num_posts_132
      t.string :subreddit_133
      t.integer :num_posts_133
      t.string :subreddit_134
      t.integer :num_posts_134
      t.string :subreddit_135
      t.integer :num_posts_135
      t.string :subreddit_136
      t.integer :num_posts_136
      t.string :subreddit_137
      t.integer :num_posts_137
      t.string :subreddit_138
      t.integer :num_posts_138
      t.string :subreddit_139
      t.integer :num_posts_139
      t.string :subreddit_140
      t.integer :num_posts_140
      t.string :subreddit_141
      t.integer :num_posts_141
      t.string :subreddit_142
      t.integer :num_posts_142
      t.string :subreddit_143
      t.integer :num_posts_143
      t.string :subreddit_144
      t.integer :num_posts_144
      t.string :subreddit_145
      t.integer :num_posts_145
      t.string :subreddit_146
      t.integer :num_posts_146
      t.string :subreddit_147
      t.integer :num_posts_147
      t.string :subreddit_148
      t.integer :num_posts_148
      t.string :subreddit_149
      t.integer :num_posts_149
      t.string :subreddit_150
      t.integer :num_posts_150
      t.string :subreddit_151
      t.integer :num_posts_151
      t.string :subreddit_152
      t.integer :num_posts_152
      t.string :subreddit_153
      t.integer :num_posts_153
      t.string :subreddit_154
      t.integer :num_posts_154
      t.string :subreddit_155
      t.integer :num_posts_155
      t.string :subreddit_156
      t.integer :num_posts_156
      t.string :subreddit_157
      t.integer :num_posts_157
      t.string :subreddit_158
      t.integer :num_posts_158
      t.string :subreddit_159
      t.integer :num_posts_159
      t.string :subreddit_160
      t.integer :num_posts_160
      t.string :subreddit_161
      t.integer :num_posts_161
      t.string :subreddit_162
      t.integer :num_posts_162
      t.string :subreddit_163
      t.integer :num_posts_163
      t.string :subreddit_164
      t.integer :num_posts_164
      t.string :subreddit_165
      t.integer :num_posts_165
      t.string :subreddit_166
      t.integer :num_posts_166
      t.string :subreddit_167
      t.integer :num_posts_167
      t.string :subreddit_168
      t.integer :num_posts_168
      t.string :subreddit_169
      t.integer :num_posts_169
      t.string :subreddit_170
      t.integer :num_posts_170
      t.string :subreddit_171
      t.integer :num_posts_171
      t.string :subreddit_172
      t.integer :num_posts_172
      t.string :subreddit_173
      t.integer :num_posts_173
      t.string :subreddit_174
      t.integer :num_posts_174
      t.string :subreddit_175
      t.integer :num_posts_175
      t.string :subreddit_176
      t.integer :num_posts_176
      t.string :subreddit_177
      t.integer :num_posts_177
      t.string :subreddit_178
      t.integer :num_posts_178
      t.string :subreddit_179
      t.integer :num_posts_179
      t.string :subreddit_180
      t.integer :num_posts_180
      t.string :subreddit_181
      t.integer :num_posts_181
      t.string :subreddit_182
      t.integer :num_posts_182
      t.string :subreddit_183
      t.integer :num_posts_183
      t.string :subreddit_184
      t.integer :num_posts_184
      t.string :subreddit_185
      t.integer :num_posts_185
      t.string :subreddit_186
      t.integer :num_posts_186
      t.string :subreddit_187
      t.integer :num_posts_187
      t.string :subreddit_188
      t.integer :num_posts_188
      t.string :subreddit_189
      t.integer :num_posts_189
      t.string :subreddit_190
      t.integer :num_posts_190
      t.string :subreddit_191
      t.integer :num_posts_191
      t.string :subreddit_192
      t.integer :num_posts_192
      t.string :subreddit_193
      t.integer :num_posts_193
      t.string :subreddit_194
      t.integer :num_posts_194
      t.string :subreddit_195
      t.integer :num_posts_195
      t.string :subreddit_196
      t.integer :num_posts_196
      t.string :subreddit_197
      t.integer :num_posts_197
      t.string :subreddit_198
      t.integer :num_posts_198
      t.string :subreddit_199
      t.integer :num_posts_199

      t.timestamps
    end
  end
end
